#!/usr/bin/env node
/**
 * Generates the adapters for non-native CLIs from the canonical source.
 *
 * Canonical source (edited by hand):
 *   agents/*.md, skills/<name>/SKILL.md, hooks/messages/*.md,
 *   .claude-plugin/plugin.json, package.json
 *
 * Generated (do NOT edit by hand):
 *   AGENTS.md, GEMINI.md, gemini-extension.json,
 *   .codex-plugin/plugin.json, .codex/hooks.json, .codex/config.toml
 *   + "version" field propagated to every manifest
 *
 * Usage:
 *   node scripts/build.mjs            writes the files
 *   node scripts/build.mjs --check    compares only; exits 1 if they diverge
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const BANNER = '<!-- GENERATED by scripts/build.mjs — do not edit by hand -->';

const read = (rel) => readFileSync(join(ROOT, rel), 'utf8');
const readJson = (rel) => JSON.parse(read(rel));

/** Extracts the fields of interest from an agent file's YAML frontmatter. */
function parseFrontmatter(text) {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const fields = {};
  let key = null;
  for (const line of match[1].split(/\r?\n/)) {
    const start = line.match(/^([a-zA-Z_]+):\s*(.*)$/);
    if (start) {
      key = start[1];
      fields[key] = start[2].trim();
    } else if (key && line.trim()) {
      // value continuing on the next line
      fields[key] += ' ' + line.trim();
    }
  }
  for (const k of Object.keys(fields)) {
    fields[k] = fields[k].replace(/^["']|["']$/g, '');
  }
  return fields;
}

function readAgents() {
  return readdirSync(join(ROOT, 'agents'))
    .filter((f) => f.endsWith('.md'))
    .sort()
    .map((file) => ({ file, ...parseFrontmatter(read(join('agents', file))) }));
}

function listSkills() {
  return readdirSync(join(ROOT, 'skills'), { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(ROOT, 'skills', d.name, 'SKILL.md')))
    .map((d) => d.name)
    .sort();
}

const readMessage = (name) => read(join('hooks', 'messages', `${name}.md`)).trim();

/**
 * Context file for CLIs without subagents and without (necessarily) hooks.
 * Serves both Codex/Antigravity (AGENTS.md) and Gemini (GEMINI.md).
 */
function buildContextFile({ skills, agents, orchestrator, planApproved }) {
  const imports = skills.map((s) => `@./skills/${s}/SKILL.md`).join('\n');

  const personas = agents
    .map(
      (a) =>
        `### ${a.name}\n\n` +
        `${a.description}\n\n` +
        `Tools: ${a.tools || 'unspecified'}.\n\n` +
        `This CLI has no native subagents. When the situation above occurs, ` +
        `adopt the behavior described in \`agents/${a.file}\` inline, in your own ` +
        `reply, instead of delegating.`
    )
    .join('\n\n');

  return `${imports}

# Lightstrator

Orchestration harness ported to this CLI from the native Claude Code plugin.
The skills above are imported; the routing and personas below replace the
features this CLI does not have.

## Prerequisites

The **caveman** plugin is required — the agents delegate the compressed reply
style to it, and \`code-reviewer\` uses the \`/caveman-review\` format.
Install it in this CLI before Lightstrator. See \`docs/PREREQUISITES.md\`.

## Mandatory routing

${orchestrator}

## Executing an approved plan

This CLI has neither plan mode nor the hook that announces approval. When a
plan is approved by the user — through \`writing-plans\` or any other path —
apply the same protocol:

${planApproved}

## Personas

The agents below exist as native subagents in Claude Code. Here they are
personas: take on the matching role when the described situation occurs.

${personas}

${BANNER}
`;
}

function buildCodexHooks(orchestrator) {
  // Codex does not expand ${CLAUDE_PLUGIN_ROOT}, so the message goes inline.
  // Single quotes are escaped to survive the shell's echo '...'.
  const escaped = orchestrator.replace(/'/g, `'\\''`);
  return {
    hooks: {
      UserPromptSubmit: [
        {
          hooks: [
            {
              type: 'command',
              command: `echo '${escaped}'`,
              timeout: 5,
            },
          ],
        },
      ],
    },
  };
  // The plan-mode hook is omitted: Codex has no plan mode.
}

function build() {
  const pkg = readJson('package.json');
  const plugin = readJson('.claude-plugin/plugin.json');
  const marketplace = readJson('.claude-plugin/marketplace.json');
  const { version } = pkg;

  const context = buildContextFile({
    skills: listSkills(),
    agents: readAgents(),
    orchestrator: readMessage('orchestrator'),
    planApproved: readMessage('plan-approved'),
  });

  // Propagates the version to the canonical manifests.
  plugin.version = version;
  marketplace.plugins = marketplace.plugins.map((p) =>
    p.name === pkg.name ? { ...p, version } : p
  );

  const codexPlugin = {
    name: plugin.name,
    version,
    description: plugin.description,
    author: plugin.author,
    homepage: plugin.homepage,
    repository: plugin.repository,
    license: plugin.license,
    keywords: plugin.keywords,
    skills: './skills/',
    hooks: {},
  };

  const geminiExtension = {
    name: plugin.name,
    description: plugin.description,
    version,
    contextFileName: 'GEMINI.md',
  };

  const json = (obj) => JSON.stringify(obj, null, 2) + '\n';

  return {
    '.claude-plugin/plugin.json': json(plugin),
    '.claude-plugin/marketplace.json': json(marketplace),
    'AGENTS.md': context,
    'GEMINI.md': context,
    'gemini-extension.json': json(geminiExtension),
    '.codex-plugin/plugin.json': json(codexPlugin),
    '.codex/hooks.json': json(buildCodexHooks(readMessage('orchestrator'))),
    '.codex/config.toml': '[features]\nhooks = true\n',
  };
}

const outputs = build();
const stale = [];

for (const [rel, content] of Object.entries(outputs)) {
  const path = join(ROOT, rel);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === content) continue;

  if (CHECK) {
    stale.push(rel);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`written: ${rel}`);
  }
}

if (CHECK) {
  if (stale.length) {
    console.error('Stale artifacts:\n  ' + stale.join('\n  '));
    console.error('\nRun `npm run build` and commit the result.');
    process.exit(1);
  }
  console.log('All generated artifacts are up to date.');
} else if (!Object.keys(outputs).length) {
  console.log('nothing to do');
}
